@set allusersprofile=c:\programdata
@set appdata=c:\users\rtx40\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=rtx4080_user
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files\microsoft visual studio\18\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set efc_19728_1262719628=1
@set efc_19728_1592913036=1
@set efc_19728_2283032206=1
@set efc_19728_2775293581=1
@set efc_19728_344590478=1
@set efc_19728_3789132940=1
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set external_include=c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\include;c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\atlmfc\include;c:\program files\microsoft visual studio\18\community\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.26100.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\cppwinrt
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set homedrive=c:
@set homepath=\users\rtx40
@set include=c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\include;c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\atlmfc\include;c:\program files\microsoft visual studio\18\community\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.26100.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\cppwinrt
@set lib=c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\atlmfc\lib\x64;c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\lib\x64;c:\program files (x86)\windows kits\10\lib\10.0.26100.0\ucrt\x64;c:\program files (x86)\windows kits\10\\lib\10.0.26100.0\\um\x64
@set libpath=c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\atlmfc\lib\x64;c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\lib\x64;c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.26100.0;c:\program files (x86)\windows kits\10\references\10.0.26100.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\rtx40\appdata\local
@set logonserver=\\rtx4080_user
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set number_of_processors=16
@set oculusbase=c:\program files\oculus\
@set onedrive=c:\users\rtx40\onedrive
@set os=windows_nt
@set path=c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\bin\hostx64\x64;c:\program files\microsoft visual studio\18\community\common7\ide\vc\vcpackages;c:\program files\microsoft visual studio\18\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files\microsoft visual studio\18\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files\microsoft visual studio\18\community\msbuild\current\bin\roslyn;c:\program files\microsoft visual studio\18\community\team tools\diagnosticshub\collector;c:\program files\microsoft visual studio\18\community\common7\ide\extensions\microsoft\codecoverage.console;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\\x64;c:\program files (x86)\windows kits\10\bin\\x64;c:\program files\microsoft visual studio\18\community\\msbuild\current\bin\amd64;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files\microsoft visual studio\18\community\common7\ide\;c:\program files\microsoft visual studio\18\community\common7\tools\;c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x64;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x86;c:\program files\microsoft visual studio\18\community\common7\tools;c:\program files\microsoft visual studio\18\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\oculus\support\oculus-runtime;c:\program files (x86)\common files\oracle\java\java8path;c:\program files (x86)\common files\oracle\java\javapath;c:\program files (x86)\razer chroma sdk\bin;c:\program files\razer chroma sdk\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files (x86)\nvidia corporation\physx\common;c:\windows\system32\config\systemprofile\appdata\local\microsoft\windowsapps;c:\program files (x86)\razer\chromabroadcast\bin;c:\program files\razer\chromabroadcast\bin;c:\users\rtx40\appdata\local\microsoft\windowsapps;c:\program files\nvidia corporation\nvidia app\nvdlisr;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;c:\program files\git\cmd;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\cmake\bin;c:\users\rtx40\appdata\local\microsoft\windowsapps;c:\jetbrains\clion 2025.2.1\bin\cmake\win\x64\bin;c:\users\rtx40\appdata\local\programs\ollama;c:\users\rtx40\appdata\local\programs\python\python310\scripts\;c:\users\rtx40\appdata\local\programs\python\python310\;c:\users\rtx40\appdata\local\programs\microsoft vs code\bin;c:\users\rtx40\.dotnet\tools;c:\program files\microsoft visual studio\18\community\common7\ide\privateassemblies\runtimes\win-x64\native;c:\program files\microsoft visual studio\18\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files\microsoft visual studio\18\community\common7\ide\commonextensions\microsoft\cmake\ninja;c:\program files\microsoft visual studio\18\community\common7\ide\vc\linux\bin\connectionmanagerexe;c:\program files\microsoft visual studio\18\community\vc\vcpkg
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\rtx40\appdata\local\microsoft\visualstudio\18.0_ea3dc07c\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=amd64 family 25 model 97 stepping 2, authenticamd
@set processor_level=25
@set processor_revision=6102
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_current=c:\program files\microsoft visual studio\18\community\msbuild
@set pvsbuildtools_extensionspath_vs2026=c:\program files\microsoft visual studio\18\community\msbuild
@set pvsbuildtools_installdir_current=c:\program files\microsoft visual studio\18\community
@set pvsbuildtools_installdir_vs2026=c:\program files\microsoft visual studio\18\community
@set pvsbuildtools_netcoresdkmajorversion=9
@set pvsbuildtools_vctargetspath_current=c:\program files\microsoft visual studio\18\community\msbuild\microsoft\vc\v180\
@set pvsbuildtools_visualstudioversion_current=18.0
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\9.0.100\sdks
@set servicehubhostservicebrokerpipename=\\.\pipe\39a5659d-8322-4aa2-9957-cf4b09a221be
@set servicehublogsessionkey=c3d976ff
@set sessionname=console
@set signinwithhometenantonly=false
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\rtx40\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\rtx40\appdata\local\temp
@set ucrtversion=10.0.26100.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=rtx4080_user
@set userdomain_roamingprofile=rtx4080_user
@set username=rtx40
@set userprofile=c:\users\rtx40
@set vcideinstalldir=c:\program files\microsoft visual studio\18\community\common7\ide\vc\
@set vcinstalldir=c:\program files\microsoft visual studio\18\community\vc\
@set vcpkg_root=c:\program files\microsoft visual studio\18\community\vc\vcpkg
@set vctoolsinstalldir=c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\
@set vctoolsredistdir=c:\program files\microsoft visual studio\18\community\vc\redist\msvc\14.50.35710\
@set vctoolsversion=14.50.35717
@set visualstudiodir=c:\users\rtx40\documents\visual studio 18
@set visualstudioedition=microsoft visual studio community 2026
@set visualstudioversion=18.0
@set vs180comntools=c:\program files\microsoft visual studio\18\community\common7\tools\
@set vsappiddir=c:\program files\microsoft visual studio\18\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=18.2.0
@set vsinstalldir=c:\program files\microsoft visual studio\18\community\
@set vslang=1055
@set vspermonitordpiawarenessenabled.10104=true
@set vsskuedition=community
@set vs_perf_session_gcheapcount=2
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.26100.0;c:\program files (x86)\windows kits\10\references\10.0.26100.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.26100.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.26100.0\
@set windowssdkversion=10.0.26100.0\
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __pslockdownpolicy=0
@set __vscmd_preinit_path=c:\program files\microsoft visual studio\18\community\vc\tools\msvc\14.50.35717\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x64;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x86;c:\program files\microsoft visual studio\18\community\common7\tools;c:\program files\microsoft visual studio\18\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\oculus\support\oculus-runtime;c:\program files (x86)\common files\oracle\java\java8path;c:\program files (x86)\common files\oracle\java\javapath;c:\program files (x86)\razer chroma sdk\bin;c:\program files\razer chroma sdk\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files (x86)\nvidia corporation\physx\common;c:\windows\system32\config\systemprofile\appdata\local\microsoft\windowsapps;c:\program files (x86)\razer\chromabroadcast\bin;c:\program files\razer\chromabroadcast\bin;c:\users\rtx40\appdata\local\microsoft\windowsapps;c:\program files\nvidia corporation\nvidia app\nvdlisr;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;c:\program files\git\cmd;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\cmake\bin;c:\users\rtx40\appdata\local\microsoft\windowsapps;c:\jetbrains\clion 2025.2.1\bin\cmake\win\x64\bin;c:\users\rtx40\appdata\local\programs\ollama;c:\users\rtx40\appdata\local\programs\python\python310\scripts\;c:\users\rtx40\appdata\local\programs\python\python310\;c:\users\rtx40\appdata\local\programs\microsoft vs code\bin;c:\users\rtx40\.dotnet\tools;c:\program files\microsoft visual studio\18\community\common7\ide\privateassemblies\runtimes\win-x64\native

@call "cl.exe" @"C:\ShadowStrike\ShadowStrike\JSONUtils.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1